### ISSUE TITLE
Error when trying to edit customer

### ISSUE THREAD

**Issue by kaspart** [Vinai/customer-activation#75]
I have installed Customer Activation, Group Catalog2 and both are active.  They work from the front end, but I cannot edit a customer.
I installed and then uninstalled LoginLog because I could not get it working (free gmail address).  Maybe the problem stems from unistallation?  I really like the way these modules work and I don't want to have to start over - maybe I just need to edit an attribute?  I have downloaded and installed the latest version of customer activation several times. 

There has been an error processing your request
Source model "customeractivation/resource_attribute_source_Customerpayment" not found for attribute "paymentmethods"

Trace:
#0 /home/sportcl1/public_html/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Source model "c...')
#1 /home/sportcl1/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(203): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /home/sportcl1/public_html/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/Account.php(75): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 /home/sportcl1/public_html/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tabs.php(58): Mage_Adminhtml_Block_Customer_Edit_Tab_Account->initForm()
#4 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Customer_Edit_Tabs->_beforeToHtml()
#5 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#6 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#7 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#8 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#9 /home/sportcl1/public_html/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#10 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/sportcl1/...')
#11 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#12 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#13 /home/sportcl1/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#14 /home/sportcl1/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#15 /home/sportcl1/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#16 /home/sportcl1/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#17 /home/sportcl1/public_html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(151): Mage_Core_Controller_Varien_Action->renderLayout()
#18 /home/sportcl1/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CustomerController->editAction()
#19 /home/sportcl1/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#20 /home/sportcl1/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#21 /home/sportcl1/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#22 /home/sportcl1/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#23 /home/sportcl1/public_html/index.php(87): Mage::run('', 'store')
#24 {main}

**Comment by kaspart** [comment]
PS - The extension works properly.  Just will not let me view or edit a customer.

**Comment by Vinai** [comment]
The file you are referencing is strange: `customeractivation/resource_attribute_source_Customerpayment`
Neither the GroupsCatalog2 nor the CustomerActivation module do anything with payments. Its definitely not something Ive written. Given the part in from of the `/` it looks like a custom extension to the module. 
Is that possible?

**Comment by kaspart** [comment]
I downloaded the extensions several times directly from Github.  I took a chance and searched my database for customeractivation and deleted three rows in the eav_attribute file.  The fist row was payment methods. Now I can edit the customer.  I haven't tried to reload the modules, but I will today.

**Comment by Vinai** [comment]
If you found the culprit, great. No need to re-download and re-install the modules in my opinion.

**Comment by gayatri34** [comment]
I am facing same issue. Please help me with the solution.

**Comment by scientic** [comment]
Same here. I am using Magento 1.8 (alpha). Even when the extension is disabled this same error occurs. However I can not find the lines in the database to delete. Even when trying to uninstall following instructions no luck. SQL replies there is no such attribute_code.

**Comment by Vinai** [comment]
@gayatri34 , do you also experience the issue with `customeractivation/resource_attribute_source_Customerpayment`? If so, just remove the corresponding record from the `eav_attribute` table.

**Comment by gayatri34** [comment]
not able to understand which record should I delete

**Comment by gayatri34** [comment]
even I am trying to uninstall your module still it is giving me errors

**Comment by scientic** [comment]
I had the same, look in the eav_attribute table for lines that refer to customeractivation. Delete them helped me. I think they were not placed there by this extension but another. Could be a name conflict

**Comment by gayatri34** [comment]
mg_customer_eav_attribute
mg_customer_eav_attribute_website

in which table should i alter

**Comment by scientic** [comment]
just 'eav_attribute'. the only addition by this plugin, I think, is the attribute code called 'customer_activated' in that table

**Comment by gayatri34** [comment]
I have removed corresponding lines but still giving error

**Comment by scientic** [comment]
same error or a different one? after clean up I went through the whole install again and then got it working. Don't forget to clean cache everytime

**Comment by gayatri34** [comment]
Now it's working but I am not able to understand from where I will approve the customer account in admin panel

**Comment by scientic** [comment]
customers > managecustomers > account information, or from the list of customers click in front of a row and on the right top change action

**Comment by gayatri34** [comment]
options are not working blank page is coming. I think I need to install it again

**Comment by gayatri34** [comment]
updated again but not working  :(

**Comment by kaspart** [comment]
gayatri34:  I kept deleting the attribute not found (3 or 4 of them) until I stopped getting the error.  They were all in the same table.  I searched for cutomeractivation in phpmyadmin - deleted the line then got a new error - deleted that one.  Sorry I did not keep a record of the ones I deleted.

**Comment by pyrophoenix14** [comment]
To resolve this issue you will need to go to eav_attribute on your MySQL database and delete the 3 following attribute:
- paymentmethods
- store_type
- iswebsite_live

Or run in MySQL:

DELETE FROM eav_attribute WHERE paymentmethods;
DELETE FROM eav_attribute WHERE store_type;
DELETE FROM eav_attribute WHERE iswebsite_live;

**Comment by chaundy** [comment]
Hi, i too had the error as above '   There has been an error processing your request
Source model "customeractivation/resource_attribute_source_Customerpayment" not found for attribute "paymentmethods"    '  in Magento 1.9.2CE.

Thank you " pyrophoenix14 " the SQL command did not work for me but remved rows manually as above in the eav_attribute and it worked. i was very unsure if i should be removing stuff, but i took the plunge it has worked for me. admin now works.  

Thank you ALL for the contributions  here.

**Comment by ak84513** [comment]
install any customer attribute extension the go customer->manage attribute and delete attribute which attribute create error

**Comment by deva24619** [comment]
Search  into customeractivation in database.  remove to a three column in eav_attribute table.I had fixed this error. Thank you everybody
