### ISSUE TITLE
Uninstalled, but still cannot edit customers

### ISSUE THREAD

**Issue by christyeller** [Vinai/customer-activation#85]
The extension caused some problems with the display of my products, so I uninstalled. Now when I try to edit a customer, I get "There has been an error processing your request." When I look up the error code in the report, I see this below.  Can you help?

`a:5:{i:0;s:116:"Source model "customeractivation/resource_attribute_source_Customerpayment" not found for attribute "paymentmethods"";i:1;s:2879:"#0 /home1/starflo6/public_html/includes/src/__default.php(43919): Mage::exception('Mage_Eav', 'Source model "c...')
#1 /home1/starflo6/public_html/includes/src/Mage_Adminhtml_Block_Widget_Form.php(203): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /home1/starflo6/public_html/includes/src/Mage_Adminhtml_Block_Customer_Edit_Tab_Account.php(75): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 /home1/starflo6/public_html/includes/src/Mage_Adminhtml_Block_Customer_Edit_Tabs.php(58): Mage_Adminhtml_Block_Customer_Edit_Tab_Account->initForm()
#4 /home1/starflo6/public_html/includes/src/__default.php(2612): Mage_Adminhtml_Block_Customer_Edit_Tabs->_beforeToHtml()
#5 /home1/starflo6/public_html/includes/src/__default.php(13677): Mage_Core_Block_Abstract->toHtml()
#6 /home1/starflo6/public_html/includes/src/__default.php(2613): Mage_Core_Block_Text_List->_toHtml()
#7 /home1/starflo6/public_html/includes/src/__default.php(2331): Mage_Core_Block_Abstract->toHtml()
#8 /home1/starflo6/public_html/includes/src/__default.php(2275): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#9 /home1/starflo6/public_html/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#10 /home1/starflo6/public_html/includes/src/__default.php(3408): include('/home1/starflo6...')
#11 /home1/starflo6/public_html/includes/src/__default.php(3439): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#12 /home1/starflo6/public_html/includes/src/__default.php(3453): Mage_Core_Block_Template->renderView()
#13 /home1/starflo6/public_html/includes/src/Mage_Adminhtml_Block_Template.php(81): Mage_Core_Block_Template->_toHtml()
#14 /home1/starflo6/public_html/includes/src/__default.php(2613): Mage_Adminhtml_Block_Template->_toHtml()
#15 /home1/starflo6/public_html/includes/src/__default.php(28307): Mage_Core_Block_Abstract->toHtml()
#16 /home1/starflo6/public_html/includes/src/__default.php(14070): Mage_Core_Model_Layout->getOutput()
#17 /home1/starflo6/public_html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(151): Mage_Core_Controller_Varien_Action->renderLayout()
#18 /home1/starflo6/public_html/includes/src/__default.php(14098): Mage_Adminhtml_CustomerController->editAction()
#19 /home1/starflo6/public_html/includes/src/__default.php(18511): Mage_Core_Controller_Varien_Action->dispatch('edit')
#20 /home1/starflo6/public_html/includes/src/__default.php(18045): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#21 /home1/starflo6/public_html/includes/src/__default.php(20837): Mage_Core_Controller_Varien_Front->dispatch()
#22 /home1/starflo6/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#23 /home1/starflo6/public_html/index.php(87): Mage::run('', 'store')
#24 {main}";s:3:"url";s:76:"/index.php/admin/customer/edit/id/2275/key/4603c2a3bba655f0cfdeea6396ef7c94/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

**Comment by Vinai** [comment]
Execute the SQL statements listed in the Readme file under the section "Uninstallation"

**Comment by christyeller** [comment]
got it, figured that was it, did it this morning with success-

Christy Eller
IamChristyEller.com
970-314-1840

**Comment by ledian-hymetllari** [comment]
I think this issue is solved :-)
